version: '3' 

services: 

    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - backend

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db_backend
      volumes:
        - ./database:/var/lib/postgresql/data

    redis:  
      image: redis 
      volumes:
        - ./data:/data

    backend:  
      image: brunovianna/backend
      environment:
        - FRONT_URL=*
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_HOST=db
      depends_on:
        - redis

    frontend:  
      image: brunovianna/frontend
