version: '3' 

services: 
    redis:  
      image: redis 

    backend:  
      image: brunovianna/backend
      environment:
        - FRONT_URL=*
        - REDIS=redis
      ports: 
        - 8000:8000

      depends_on:
        - redis

    frontend:  
      image: brunovianna/frontend
      ports: 
        - 5000:5000
