version: '3' 

services: 
    backend:  
      image: brunovianna/backend
      environment:
        - FRONT_URL=*
      ports: 
        - 8000:8000

    frontend:
      image: brunovianna/frontend
      environment:
        - API_URL=http://localhost:8000
      ports: 
        - 5000:5000
